### ISSUE TITLE
entrypoint broken

### ISSUE THREAD

**Issue by kapilt** [clumio-code/azure-sdk-trim#2]
the readme documents two ways to install, using the pip install ala

`pip install git+https://github.com/clumio-code/azure-sdk-trim@v0.2.0#egg=azure-sdk-trim`

and executing azure-sdk-trim results in a traceback,

```
6.373 Successfully built azure-sdk-trim
6.662 Installing collected packages: humanize, azure-sdk-trim\
6.717 Successfully installed azure-sdk-trim-0.2.0 humanize-4.9.0
6.819 Traceback (most recent call last):
6.819   File "/app/bin/azure-sdk-trim", line 8, in <module>
6.819     sys.exit(main())
6.819              ^^^^^^
6.819 TypeError: main() missing 1 required positional argument: 'argv'
```

this is due to the entry point directly referencing the main function, which has as a required parameter on sys.argv which is not valid for the entry point. it looks like this was accidentally changed in the last commit (https://github.com/clumio-code/azure-sdk-trim/commit/265c4cd84c4a9f89caf5bda5ff5260736da2f4ba) to go from optional to required which broke a common installation/usage method.

**Comment by sodul** [comment]
@kapilt thanks for the bug report, we'll look into it this week.
